baseURL = "www.marbellasolar.com"
disqusShortname = ""
googleAnalytics = "UA-219802725-1"
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Marbella Solar"
[markup.goldmark.renderer]
unsafe = true
