baseURL = "www.marbellasolar.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Marbella Solar"
[markup.goldmark.renderer]
unsafe = true
