author = "Santiago Llera"
blogCategoryType = "category"
contact_form_action = "#"
description = "Marbella Solar by OnRenewables"
image = "images/logo.png"
logo = "images/logo.png"
logo_width = "300px"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2
[navigation_button]
enable = true
label = "Quotation"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/ONRSolarRooftops"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/on_renewables"
title = "twitter"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/onrenewables/"
title = "linkedin"
